#!/usr/bin/env python3

import os
import json
import argparse
from datetime import datetime as dt

from todo_list import TodoList
from todo_item import TodoItem
from constants import Constants

def init():
    if os.path.exists(Constants.list_fname):
      print('.todo.json already exists')
      print('remove it first with `nt rm list`')

    with open(Constants.list_fname, 'w') as f:
      todo_list = TodoList()
      todo_list.to_file()
      print('successfully created {}'.format(Constants.list_fname))

def main():
  parser = argparse.ArgumentParser('nt')

  subparsers = parser.add_subparsers(dest='cmd')
  init_subparser = subparsers.add_parser('init')
  add_subparser = subparsers.add_parser('add', aliases=['a'])
  rm_subparser = subparsers.add_parser('rm', aliases=['r', 'd'])
  ls_subparser = subparsers.add_parser('ls', aliases=['l'])

  add_subparser.add_argument('content', help='content')
  add_subparser.add_argument('-d', '--due', help='due date', type=str)
  add_subparser.add_argument('-p', '--priority', help='priority', type=int)

  args = parser.parse_args()
  print(args)

  if args.cmd is None:
    parser.print_usage()
    exit(0)

  if args.cmd == 'init':
    init()
    exit(0)

  if args.cmd in ['a', 'add']:
    todo_list = TodoList.from_file(Constants.list_fname)
    due = None if args.due is None else dt.strptime(args.due, '%d.%m.%Y %H:%M:%S')
    item = TodoItem(
      todo_list.max_id+1,
      args.content,
      due,
      args.priority)
    todo_list.add_item(item)
    todo_list.to_file()
    exit(0)

  if args.cmd in ['l', 'ls']:
    todo_list = TodoList.from_file(Constants.list_fname)
    for item in todo_list.items:
      print(item)

if __name__ == '__main__':
  main()
